import java.util.ArrayList;
import java.util.Collections;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jessegrimes' at '2/15/17 6:04 PM' with Gradle 2.13
 *
 * @author jessegrimes, @date 2/15/17 6:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    
    	ArrayList<String> J = new ArrayList<String>();
    	String[] list = {"a", "b", "jill", "abc"};
      for(String j: list)
      {
    	  J.add(j);
      }
      
     Collections.sort(J);
       list.equals(J);
        return true;
    }
}
